### PR TITLE
Add YouTube clone page 

### PR DESCRIPTION
**Pull request by abredi**
- Use HTML and CSS only and add font awesome for icons

- Use html-validator-cli for validating index.html page 

- use stylelint and stylelint-config-recommended for linting style.css

### CODE REVIEW

**Comment by adaorachi** [comment]
### **Hi @abredi and @AdesojiCodeMaster** ,

Amazing work on your very first project. You guys did really well! 💯 

- The clone shows a good understanding and usage of embedding images and videos.
- The cloned page is rendering as it should and meets almost all the project specifications.
- The project has a descriptive README.md content and is professionally done.
- Pull Request has a descriptive summary and your commit messages are very meaningful.
- The markup as well is clean and has no errors nor warnings to show. 
- The repo has followed the guidelines for GitHub flow/Git flow.
- And I also like the use of favicon. It looks nice on the browser title tab.
Good Job! 👍 

**However, there are a couple of changes you will need to make to get an approval for this project. 
You are just away from completing this project! 💪** 

---
### **CHANGES REQUIRED** ♻️ 
---

- [ ]  First, your repo contains files that are not related to the project and which should not be committed. Some folders in the asset/font folder should not be added to your commits. You only need the Webfont folder for your icons. 
Create a .gitignore file in the root folder of your project and include those list of folders/files to ignore while making commits. Another option and better one is to use the font-awesome CDN link to include icons into your project like this - 
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">`

---

- [ ] From the requirement of this project in the pathwright, it says -
 `**This project consists of building an HTML document that matches the appearance of youtube video player page.**`
With this, you should ensure your page layout looks very similar to the original YouTube page.
In the highlighted area in the screenshot below, the navbar should have at least three embedded images on the rightmost side that represents icons and/or an avatar.
Also, see the requirement screenshot from Odin Project [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png).
Please refer to the [YouTube Link](https://www.youtube.com/watch?v=V74l_zS1x8E) for more clarification.

**YOUR PROJECT VERSION:**

yt1

---

- [ ] Next, in reference to my previous comment, you should also ensure that the video contents; the title, number of views, icons, buttons, and user avatar should be aligned and positioned similarly to that of the original page. See the screenshot below for reference. Use the original page to compare differences.

**YOUR PROJECT VERSION:**

yt2

---

**The following requirements are NOT MANDATORY but I would encourage you to take a moment to look into them as they will be helpful in future projects.**

---

- [optional] Ensure that all your images are in one folder so as to keep your files clean and compact.

---

- [optional] You should ensure the good usage of semantic HTML codes. I should have made this commented in a highlighted section of your codes but it almost impossible to load that page because of the tons of files in there. 
You have two `aside` semantic tags with contents in your HTML markup. You should consider changing the content tag that has the video to `main` tag. This correctly defines the content of that section since it is the main content.
Also, consider using the `nav` tag for your navigation bar.

---

- [ ] You should also consider making your Sidebar contents clickable. Enclose each of the thumbnail and their contents with anchor tags. This helps to improve the user interface.

--- 

- [ ] Linter checks are not required for this project.  But since you have it set up for this project, it would be nice if you put in extra effort to make your CSS code pass the validations.

---

**NOTE: All requirements not marked with [optional] are mandatory!**

### **After implementing the MANDATORY changes highlighted above, request for another review by submitting a Code Review Form.** 

Should you have any questions or need any help, please feel free to reach out to me on Slack with the username (@adaorachi). ☺️ 

**Happy Coding and Good-luck on it.**

**MaryAnn Chukwuka**

**Comment by abredi** [comment]
@adaorachi We have fixed all the issues you have mentioned and improve the page based on your suggestions.

**Comment by adaorachi** [comment]
Hi @abredi, good job on implementing the changes. You can now submit another Code Review Form from your dashboard.

**Comment by trekab** [comment]
Hi @abredi and @AdesojiCodeMaster, well done with the earlier requested changes! :+1:  We have a few more to get done with this project.

# Changes Required:
- [ ] Make sure that all stickler checks are passing.
- [ ] [Your clone](https://rawcdn.githack.com/abredi/youtube-clone/feature/youtube-landing-page/index.html)'s __subscribe button, like and dislike icons, share button, number of views__ are not in the right positions compared to the [original site](https://www.youtube.com/watch?v=sp2VhLClSUU).

__Please, implement the above changes and submit another code review request.
_Feel free to reach me on slack for any inquiries about this review_
__Treasure Kabareebe__

**Comment by trekab** [comment]
__N.B:__ The stickler checks are an __optional__ requirement like @adaorachi indicated. I should have indicated that in my above review.

_All the best, __team__!_ :wink:

**Comment by abredi** [comment]
@trekab I think the current YouTube page _video primary info renderer_ section is quite different from the older version that we are working on

**Comment by MarioDena** [comment]
Hello! Good work on your project, however please be sure that there are no conflicting files on the branch you are trying to merge. 
Cheers!

**Pull request closed without merging**
